#!/bin/bash
app_type=$1
github_project_name="ProjectHindsight/2020.git"
remote_source="$(git config --get remote.origin.url | grep $github_project_name)"
root_dir="$(git rev-parse --show-toplevel)"
proj_name="$(basename $root_dir)"
original_dir=$(pwd)

if [[ -n $remote_source ]]; then
  if [[ $app_type = "client" ]]; then
    (cd $root_dir/client && npm install && npx cap open ios ; cd $original_dir)
  elif [[ $app_type = "debug" ]]; then
    (cd $root_dir/client && npm install && npm run serve ; cd $original_dir)
  elif [[ $app_type = "server" ]]; then
    (cd $root_dir/server && poetry install && poetry run python app.py ; cd $original_dir)
  else
    echo -e "Enter \033[1;32mserver\033[0m, \033[1;32mclient\033[0m, or \033[1;32mdebug\033[0m as args (e.g. \033[1;3m'2020 debug'\033[0m)"
  fi
else
  echo -e "Please cd into \033[1;32m2020\033[0m project root directory."
fi
